version: "3.8"

services:
        ####Eye-Beacon: Version 1 -- Web Service#####
        web-service:
                container_name: "webservice"
                image: "eye-beacon/web-service:1.0.0"
                restart: always
                stdin_open: true
                tty: true
                command: -u 0.0.0.0 -p 5001 -r redis
                ports:
                        - "5001:5001"
                depends_on: 
                        - redis
                cpus: 0.25

        ####Eye-Beacon: Version 1 -- People Counter#####
        people-counter:
                container_name: "people-counter"
                image: "eye-beacon/people-counter:1.0.0"
                stdin_open: true
                tty: true
                command: -i rtsp://192.168.0.107:8554/cam --prototxt ./ai/mobilenet_ssd/MobileNetSSD_deploy.prototxt --model ./ai/mobilenet_ssd/MobileNetSSD_deploy.caffemodel -u http://192.168.0.107:5001//eyebeacon/dashboard/counter -r localhost
                restart: always
                depends_on: 
                        - redis
                        - webservice
                cpus: 10

        ####Eye-Beacon: Version 1 -- Desktop Dashboard#####
        dekstop-dashboard:
                container_name: "dekstop-dashboard"
                image: "eye-beacon/desktop-dashboard:1.0.0"
                stdin_open: true
                tty: true
                command: -r redis
                environment: 
                        - DISPLAY=172.18.48.1:1.0
                restart: always
                depends_on: 
                        - redis
                cpus: 1.5

        ####Redis#####
        redis:
                container_name: "redis"
                image: redis:alpine
                restart: always
                volumes:
                        - ./.docker/redis/data:/data
                command: redis-server
                ports:
                        - "6379:6379"
                cpus: 0.25